export const SITE_CONFIG = {
  name: "Dr. Mohamed Sediq Howdy",
  title: "Professor of Neurosurgery and Spine Surgery",
  subtitle: "Faculty of Medicine – Cairo University",
  phone: "+2 010 05568333",
  whatsapp: "201005568333",
  email: "info@drhowdy.com",
  appointmentsEmail: "appointments@drhowdy.com",
  emergencyEmail: "emergency@drhowdy.com",
  emergencyPhone: "+20 2 2365 8742",
  copyright: "© 2024 Dr. Mohamed Sediq Howdy. All rights reserved.",
};

export const CLINICS = [
  {
    name: "Al Riyadh Hospital – Mohandessin",
    address: "10 Riyadh St., off Shehab St. – Mohandessin",
    phones: ["023 774 3600", "0114 454 4460", "0100 160 2044", "01550123906", "01147611661"],
    days: "Every Saturday",
    hours: "2:00 PM – 6:00 PM",
    note: "Calls daily 11:00 AM – 5:00 PM (except Friday). Consultations by prior appointment only.",
    whatsapp: "",
  },
  {
    name: "Giza Clinic",
    address: "1 El-Gamaa St., above Old Omar Effendi – Giza Square",
    phones: ["023 774 3600", "0114 454 4460", "0100 160 2044"],
    days: "Saturday, Tuesday",
    hours: "6:00 PM – 9:00 PM",
    whatsapp: "201001234567",
  },
  {
    name: "6th of October Clinic",
    address: "Central Axis – Diamond Mall – Tower (D), next to Magda Cinema Complex",
    phones: ["023 774 3600", "0114 454 4460", "0100 160 2044"],
    days: "Sunday, Wednesday",
    hours: "6:00 PM – 9:00 PM",
    whatsapp: "201012345678",
  },
  {
    name: "Fayoum Clinic",
    address: "El-Soufy, next to Fire Station, above Abdel Nasser Pharmacy",
    phones: ["023 774 3600", "0114 454 4460", "0100 160 2044"],
    days: "Monday",
    hours: "10:00 AM – 5:00 PM",
    whatsapp: "201023456789",
  },
];

export const SERVICES = [
  {
    slug: "lumbar-discectomy",
    title: "Minimally Invasive Lumbar Discectomy",
    category: "Minimally Invasive Surgery",
    description: "Advanced procedure for herniated discs with minimal disruption.",
    conditions: ["Herniated Lumbar Disc", "Sciatica", "Radiculopathy"],
    type: "Minimally Invasive Surgery",
  },
  {
    slug: "cervical-fusion",
    title: "Cervical Spine Fusion",
    category: "Cervical Disorders",
    description: "Stabilizing the neck to relieve nerve compression and pain.",
    conditions: ["Cervical Degenerative Disc Disease", "Spinal Stenosis", "Cervical Radiculopathy", "Myelopathy"],
    type: "Open Surgery",
  },
  {
    slug: "endoscopic-surgery",
    title: "Endoscopic Spine Surgery",
    category: "Microscopic/Endoscopic",
    description: "High-precision surgery using an endoscope for various spinal conditions.",
    conditions: ["Lumbar Disc Herniation", "Spinal Stenosis", "Foraminal Stenosis"],
    type: "Endoscopic Surgery",
  },
  {
    slug: "deformity-correction",
    title: "Spinal Deformity Correction",
    category: "Deformities",
    description: "Surgical correction for scoliosis, kyphosis, and other spinal curvatures.",
    conditions: ["Scoliosis", "Kyphosis", "Spondylolisthesis", "Spinal Imbalance"],
    type: "Complex Reconstructive Surgery",
  },
  {
    slug: "pain-management",
    title: "Chronic Back Pain Management",
    category: "Pain Clinic",
    description: "Comprehensive strategies for long-term relief from persistent back pain.",
    conditions: ["Chronic Low Back Pain", "Failed Back Surgery Syndrome", "Neuropathic Pain", "Facet Joint Syndrome"],
    type: "Interventional Pain Management",
  },
  {
    slug: "thoracic-surgery",
    title: "Thoracic Spine Surgery",
    category: "Thoracic Disorders",
    description: "Specialized surgical interventions for mid-back conditions.",
    conditions: ["Thoracic Disc Herniation", "Thoracic Myelopathy", "Thoracic Fractures", "Spinal Tumors"],
    type: "Open Surgery, Minimally Invasive Surgery",
  },
  {
    slug: "vertebroplasty",
    title: "Vertebroplasty and Kyphoplasty",
    category: "Fixation",
    description: "Minimally invasive treatments for vertebral compression fractures.",
    conditions: ["Vertebral Compression Fractures", "Osteoporosis", "Spinal Tumors"],
    type: "Minimally Invasive Percutaneous Procedure",
  },
  {
    slug: "neural-injury",
    title: "Neural Injury Consultations",
    category: "Neural Injury",
    description: "Expert evaluation and guidance for nerve damage and spinal cord injuries.",
    conditions: ["Spinal Cord Injury", "Peripheral Nerve Injury", "Brachial Plexus Injury", "Nerve Entrapment"],
    type: "Consultation, Diagnostic Evaluation",
  },
  {
    slug: "online-consultation",
    title: "Online Spine Consultation",
    category: "Online Consultations",
    description: "Convenient virtual consultations for initial assessment and second opinions.",
    conditions: ["Various Spinal Conditions", "Second Opinion", "Pre-Surgical Assessment"],
    type: "Telemedicine Consultation",
  },
  {
    slug: "tumor-resection",
    title: "Spinal Cord Tumor Resection",
    category: "Advanced Neurosurgery",
    description: "Surgical removal of tumors affecting the spinal cord and surrounding structures.",
    conditions: ["Intramedullary Tumors", "Extramedullary Tumors", "Intradural Tumors", "Vertebral Tumors"],
    type: "Microsurgical Resection",
  },
];

export const TESTIMONIALS = [
  {
    name: "Ahmed Hassan",
    condition: "Lumbar Disc Herniation",
    date: "Sep 15, 2024",
    text: "After years of debilitating lower back pain due to a herniated disc, Professor Howdy performed a minimally invasive surgery that completely changed my life. I'm back to my daily activities without pain. His expertise and compassionate approach are truly remarkable.",
  },
  {
    name: "Fatima Zahra",
    condition: "Cervical Spondylosis",
    date: "Aug 28, 2024",
    text: "I suffered from severe cervical spondylosis, causing constant neck pain and numbness in my arm. Professor Howdy's precise diagnosis and advanced treatment plan, including microscopic decompression, brought me immense relief. I highly recommend him.",
  },
  {
    name: "Omar El-Sayed",
    condition: "Spinal Stenosis",
    date: "Jul 20, 2024",
    text: "My experience with Professor Howdy for my spinal stenosis was exceptional. From the initial consultation to the post-operative care, I felt fully informed and supported. The endoscopic procedure was a success, and I'm now walking without pain.",
  },
  {
    name: "Laila Mahmoud",
    condition: "Spinal Deformity",
    date: "Jun 5, 2024",
    text: "Professor Howdy gave me a second chance at a pain-free life. I had a complex spinal deformity, and other doctors were hesitant. His confidence, skill, and dedication were evident throughout my entire journey. I am forever grateful.",
  },
  {
    name: "Youssef Kamal",
    condition: "Chronic Sciatica",
    date: "May 18, 2024",
    text: "The chronic sciatica I endured for years made simple tasks impossible. Professor Howdy's pain management expertise and targeted injections provided immediate and lasting relief. His approach is truly patient-centered.",
  },
  {
    name: "Nadia Ibrahim",
    condition: "Lumbar Instability",
    date: "Apr 10, 2024",
    text: "I came to Professor Howdy for a second opinion on my lumbar instability. He took the time to explain everything in detail and offered a solution that was less invasive than what I was initially told. The results have been fantastic.",
  },
  {
    name: "Khaled Mansour",
    condition: "Complex Spinal Fusion",
    date: "Mar 22, 2024",
    text: "From the moment I met Professor Howdy, I felt I was in the best hands. His team is incredibly professional, and his surgical skills are unmatched. My recovery from a complex spinal fusion was smoother than I ever imagined.",
  },
];

export const VIDEOS = [
  {
    title: "Understanding Lumbar Disc Herniation",
    type: "Educational Clip",
    category: "Lumbar Disorders",
    description: "Professor Howdy explains the causes, symptoms, and modern treatment options for lumbar disc herniation, emphasizing minimally invasive approaches.",
    date: "Oct 15, 2023",
  },
  {
    title: "Minimally Invasive Spine Surgery: A Patient's Guide",
    type: "Educational Clip",
    category: "Minimally Invasive Surgery",
    description: "An in-depth look at the benefits and procedures of minimally invasive spine surgery, presented by Professor Howdy.",
    date: "Jan 22, 2024",
  },
  {
    title: "TV Interview: Advances in Spinal Care in Egypt",
    type: "TV Interview",
    category: "General Spine Health",
    description: "Professor Howdy discusses the latest advancements in spinal care and neurosurgery in Egypt on a popular morning show.",
    date: "Jul 1, 2023",
  },
  {
    title: "Cervical Spine Pain: Diagnosis and Treatment",
    type: "Educational Clip",
    category: "Cervical Disorders",
    description: "Learn about common causes of neck pain, diagnostic methods, and effective treatment strategies for cervical spine issues.",
    date: "Nov 5, 2023",
  },
  {
    title: "Understanding Spinal Deformities: Scoliosis & Kyphosis",
    type: "Educational Clip",
    category: "Spinal Deformities",
    description: "Professor Howdy provides an overview of spinal deformities like scoliosis and kyphosis, including early detection and surgical options.",
    date: "Mar 10, 2024",
  },
  {
    title: "Patient Testimonial: Life After Spine Surgery",
    type: "Testimonial",
    category: "Patient Stories",
    description: "A heartwarming story from a patient who underwent successful spine surgery with Professor Howdy, sharing their journey to recovery.",
    date: "Sep 18, 2023",
  },
  {
    title: "The Role of Pain Management in Chronic Back Pain",
    type: "Awareness",
    category: "Pain Management",
    description: "Explore various pain management techniques and their importance in improving the quality of life for patients with chronic back pain.",
    date: "Feb 28, 2024",
  },
  {
    title: "Inside the Operating Room: Microscopic Discectomy",
    type: "Surgery Insight",
    category: "Surgery Insights",
    description: "A brief insight into a microscopic discectomy procedure, showcasing the precision and advanced techniques used by Professor Howdy's team.",
    date: "Apr 5, 2024",
  },
];

export const BLOG_POSTS = [
  {
    slug: "future-spine-surgery-minimally-invasive",
    title: "The Future of Spine Surgery: Minimally Invasive Techniques",
    category: "Treatments",
    excerpt: "Discover how minimally invasive spine surgery offers faster recovery, less pain, and improved outcomes for various spinal conditions.",
    date: "Oct 28, 2024",
    featured: true,
  },
  {
    slug: "lumbar-disc-herniation-symptoms-causes",
    title: "Lumbar Disc Herniation: Symptoms, Causes, and When to Seek Help",
    category: "Symptoms",
    excerpt: "A comprehensive guide to understanding lower back pain caused by lumbar disc herniation, its common symptoms, and effective management strategies.",
    date: "Sep 15, 2024",
  },
  {
    slug: "spine-surgery-myths-debunked",
    title: "5 Common Myths About Spine Surgery Debunked",
    category: "Myths",
    excerpt: "Separating fact from fiction: We address and debunk common misconceptions surrounding spine surgery to help you make informed decisions.",
    date: "Aug 1, 2024",
  },
  {
    slug: "tech-neck-cervical-spine-prevention",
    title: "Battling 'Tech Neck': Preventing Cervical Spine Issues in the Modern Era",
    category: "Education",
    excerpt: "Learn practical tips and ergonomic strategies to protect your cervical spine from the strains of prolonged digital device use and prevent 'tech neck'.",
    date: "Jul 20, 2024",
  },
  {
    slug: "advanced-imaging-spine-diagnostics",
    title: "Precision Diagnostics: How Advanced Imaging Transforms Spine Care",
    category: "Education",
    excerpt: "Explore the critical role of advanced imaging technologies like MRI, CT, and X-rays in achieving accurate spinal diagnoses and guiding effective treatment plans.",
    date: "Jun 5, 2024",
  },
];

export const MEDIA = [
  {
    title: "Understanding Sciatica: A TV Interview",
    type: "TV",
    outlet: "Al-Hayat TV",
    date: "Oct 25, 2023",
    description: "Professor Howdy discusses common causes, symptoms, and modern treatment options for sciatica, emphasizing patient education and early intervention.",
    featured: true,
  },
  {
    title: "Minimally Invasive Spine Surgery: The Future of Back Pain Treatment",
    type: "Press",
    outlet: "Egypt Today Magazine",
    date: "Jan 15, 2024",
    description: "An in-depth article featuring Professor Howdy on the advancements and benefits of minimally invasive techniques in spine surgery.",
  },
  {
    title: "Keynote Speaker: World Spine Congress 2023",
    type: "Conference",
    outlet: "World Spine Congress",
    date: "Nov 8, 2023",
    description: "Professor Howdy delivered a keynote address on 'Innovations in Spinal Deformity Correction' to an international audience.",
  },
  {
    title: "Awareness Campaign: Preventing Neck and Back Pain",
    type: "Campaign",
    outlet: "Cairo University Hospital",
    date: "Mar 1, 2024",
    description: "A public health campaign led by Professor Howdy, providing practical tips and exercises to prevent common neck and back pain.",
  },
  {
    title: "Live Q&A: Lumbar Disc Herniation",
    type: "Online Event",
    outlet: "Facebook Live",
    date: "Feb 20, 2024",
    description: "Professor Howdy hosted a live online session answering patient questions about lumbar disc herniation.",
  },
  {
    title: "Interview: The Role of Technology in Modern Neurosurgery",
    type: "Podcast",
    outlet: "Medical Insights Podcast",
    date: "Sep 12, 2023",
    description: "Professor Howdy discusses how advanced imaging, robotics, and navigation systems are transforming neurosurgical procedures.",
  },
];
